#!/bin/bash
PKCS11=~/.ssh/id_rsa-1
SCRIPT_FILE=~/SSH_AGENT_SCRIPT
PID_FILE=~/JITDT_PID
DAEMON=watch_and_transfer
OPTIONS="sftp:ishikawa@hibiki.aics.riken.jp:/opt/nowcast/data/  \
    /mnt/latest-kobe/ \
    -n /home/yisikawa/nowcast/jitready:/opt/nowcast/bell/ -v -D \
    -f /home/yisikawa/nowcast/JITLOG"

#    -s 2017-0615/15/ 


case "$1" in
  start)
        echo -n "Starting jit-dt: "
	SCRIPT=`ssh-agent`
	eval $SCRIPT
	ssh-add $PKCS11
	echo $SCRIPT >$SCRIPT_FILE
	shift 1
	$DAEMON $OPTIONS $* >$PID_FILE
        echo "done"
        ;;
  stop)
        echo -n "Stopping jit-dt: "
	kill -KILL `cat $PID_FILE`
	kill -KILL `sed -e 's/.*pid \(.*\);/\1/' $SCRIPT_FILE`
        echo "done"
        ;;
  *)
        echo "Usage: jit-dt start [<options>]" >&2
        echo "       jit-dt stop" >&2
        echo "  Ex.  jit-dt start 2016-1207/10/" >&2
        exit 1
        ;;
esac

exit 0
