#!/bin/bash
TOP=~/nowcast/
PID_FILE=~/KWATCH_PID
DAEMON=kwatcher
DATADIR=/opt/nowcast/kobe/data/
LOGFILE=/opt/nowcast/kobe/KWATCHLOG
OPTIONS="-D -d -v -c /opt/nowcast/kobe/etc/conf -f $LOGFILE /opt/nowcast/kobe/bell $DATADIR"
OPTIONS2="-d -v -c /opt/nowcast/kobe/etc/conf -f $LOGFILE /opt/nowcast/kobe/bell $DATADIR"

case "$1" in
  start)
        echo -n "Removing data: "
	rm -f $DATADIR/*
	echo "done"
        echo -n "Starting kwatch: "
	echo "$DAEMON $OPTIONS $*"
	$DAEMON $OPTIONS $* >$PID_FILE
        echo "done"
	;;
  start2)
        echo -n "Removing data: "
	rm -f $DATADIR/*
	echo -n "done"
        echo -n "Starting kwatch: "
	echo "$DAEMON $OPTIONS2 $*"
	$DAEMON $OPTIONS2 $*
        ;;
  stop)
        echo -n "Stopping jit-kwatch: "
	kill -KILL `cat $PID_FILE`
        echo "done"
        ;;
  *)
        echo "Usage: jit-kwatch start [<options>]" >&2
        echo "       jit-kwatch stop" >&2
        ;;
esac

exit 0
